OINK-592 Feature/transaction detail
Alcancia-io/alcancia pull request #18
Opened 2022-09-12 01:00 UTC by juandatorr99

Utiliza para el transaction_id del char 0 hasta antes del primer guión.

2022-09-12 01:00 UTC, juandatorr99 commented
Task linked: [OINK-592 Transaction detail](https://app.clickup.com/t/24497898/OINK-592)

2022-09-13 18:08 UTC, manu-yaff commented on lib/src/features/dashboard/presentation/dashboard_card.dart
> +                        ? alcanciaCardDark2
Nicely done

2022-09-13 18:10 UTC, manu-yaff commented on lib/src/shared/extensions/string_extensions.dart
> +    return this == 'DEPOSIT' ? 'DEPOSITO' : 'RETIRO';
Yield type is missing @juandatorr99 😱

2022-09-13 18:10 UTC, manu-yaff requested changes

2022-09-13 18:10 UTC, manu-yaff commented on lib/src/shared/provider/router_provider.dart
> +      builder: (context, state) => TransactionDetail(txn: state.extra as Transaction),
Elegant

2022-09-13 18:16 UTC, manu-yaff approved these changes

2022-09-13 18:17 UTC, juandatorr99 commented on lib/src/shared/extensions/string_extensions.dart
> +    return this == 'DEPOSIT' ? 'DEPOSITO' : 'RETIRO';
thanks youuu!!

2022-09-13 18:17 UTC, juandatorr99 commented on lib/src/shared/provider/router_provider.dart
> +      builder: (context, state) => TransactionDetail(txn: state.extra as Transaction),
JAJAJJAJA 😎

2022-09-13 18:17 UTC, merged