Fix Registration Feedback
Alcancia-io/alcancia pull request #22
Opened 2022-09-20 19:50 UTC by kiwis08

2022-09-21 19:39 UTC, manu-yaff requested changes
Faltaría que el countdown se reinicie cuando le das reenviar y revisar porque el dob se guarda como 2  años más jóven

<img width="343" alt="imagen" src="https://user-images.githubusercontent.com/38588601/191595034-4ff94975-4df2-43d9-b3cf-ff2a5441677a.png">

2022-09-23 19:31 UTC, juandatorr99 requested changes
Si registra al user pero cuando va a mandarme al login no funciona sale este error.
![Screen Shot 2022-09-23 at 14 27 59](https://user-images.githubusercontent.com/31773192/192043527-d8c3ad25-6289-4922-ab5f-b93ba0a0566c.png)

2022-09-25 17:48 UTC, juandatorr99 approved these changes

2022-09-25 17:48 UTC, juandatorr99 approved these changes

2022-09-25 17:48 UTC, juandatorr99 approved these changes

2022-09-25 17:49 UTC, juandatorr99 approved these changes

2022-09-25 20:21 UTC, merged