fix: buttons in welcome, login, registration, otp and registration modal
Alcancia-io/alcancia pull request #23
Opened 2022-09-23 20:55 UTC by manu-yaff

Change button dimensions according to figma

2022-09-25 18:00 UTC, juandatorr99 approved these changes

2022-09-25 18:06 UTC, juandatorr99 requested changes
Corrige porfa el dropdown
![Screen Shot 2022-09-25 at 13 05 31](https://user-images.githubusercontent.com/31773192/192158411-5af5e1ac-7dfb-4069-ac5e-5ae31cc92729.png)

2022-09-26 16:44 UTC, manu-yaff commented
> Corrige porfa el dropdown ![Screen Shot 2022-09-25 at 13 05 31](https://user-images.githubusercontent.com/31773192/192158411-5af5e1ac-7dfb-4069-ac5e-5ae31cc92729.png)

Ese va en otro PR

2022-09-28 21:09 UTC, manu-yaff commented
@juandatorr99 revisa este porfa. Ya estoy arreglando eso en otra rama

2022-09-29 01:19 UTC, juandatorr99 approved these changes

2022-09-29 01:19 UTC, merged