My account screen
Alcancia-io/alcancia pull request #35
Opened 2022-10-24 23:41 UTC by kiwis08

## Summary
Moved delete account button to empty (for now) Account screen.
Also changed router redirect behavior to avoid adding empty conditions for every new screen

## Requirements
None

## Type of change
- [x] feature
- [ ] hotfix
- [ ] fix
- [ ] refactor
- [ ] chore
- [ ] docs

## How to test?
Log in, go to profile screen and tap on my account. Logging out and deleting your account should take you to the welcome screen.

## How has this been tested?
- [ ] Tapping on my account button takes you to new screen without routing errors in the console
- [ ] Hot restarting app redirects to correct screen

## Checklist (for the reviewer)

- [ ] Does the code compile without errors or warnings?
- [ ] Does the PR is free of merge conflicts?
- [ ] Does the UI is responsive?
- [ ] Is the PR modular?

2022-10-25 19:24 UTC, manu-yaff commented on lib/src/features/user-profile/presentation/account_screen.dart
> +  final GraphqlService _gqlService = GraphqlService();
(refactor) Este service cambió en el refactor

2022-10-25 19:25 UTC, manu-yaff commented on lib/src/features/user-profile/presentation/account_screen.dart
> +    final user = ref.watch(userProvider) ?? User.sampleUser;
(refactor)

2022-10-25 19:36 UTC, manu-yaff commented on lib/src/features/user-profile/presentation/account_screen.dart
> +  SnackBar _snackBar(BuildContext context, String string) {
Este snackbar se podría hacer un widget para poder reutilizarlo, creo que tienes código similar a este en la pantalla del OTP y el user profile

2022-10-25 19:37 UTC, manu-yaff commented on lib/src/features/user-profile/presentation/account_screen.dart
> +                                    context.goNamed("welcome");
¿Por qué aquí uasaste context.goName() y no un context.go()? Es necesario navegar por nombre? Tengo curiosidad jajaja

2022-10-25 19:38 UTC, manu-yaff commented on lib/src/features/user-profile/presentation/account_screen.dart
> +                                acceptAction: () async {
¿Se puede extrar está lógica fuere del widget y sólo pasar la función?

2022-10-25 19:43 UTC, manu-yaff commented on lib/src/shared/components/alcancia_tabbar.dart
> +      body: widget.screens[widget.selectedIndex],
Coool, así está mejor que como lo teníamos esto!

2022-10-25 19:47 UTC, manu-yaff requested changes

2022-10-25 19:47 UTC, manu-yaff commented on lib/src/shared/provider/router_provider.dart
> +        final loginLoc = state.namedLocation("login");
Diría que este cambió no va en este PR

2022-10-25 19:47 UTC, manu-yaff commented on lib/src/shared/provider/router_provider.dart
> +        final loggedIn = await isUserAuthenticated();
Esto no pude probarlo por el error que me sale cuando hago login

2022-10-25 19:47 UTC, manu-yaff commented on lib/src/shared/provider/user.dart
> +
(refactor)

2022-10-25 19:50 UTC, manu-yaff requested changes
Cuando hago login me da este error:
![imagen](https://user-images.githubusercontent.com/38588601/197868159-dc191b36-49ce-4cf4-b677-dda8123b2ece.png)

_Yo lo probé con develop en el back_

2022-10-26 05:46 UTC, juandatorr99 requested changes
Santi puedes agregarle a la sección de mi cuenta lo de cambiar contraseña y dejar el boton de borrar cuenta hasta abajo como el de logout en perfil porfa? 
<img width="270" alt="Screen Shot 2022-10-26 at 0 39 27" src="https://user-images.githubusercontent.com/31773192/197944618-3ec2af39-e857-48e4-8df1-95148285f7a2.png"> Y mover el boton de Mi Cuenta de primero (antes de terms & c y politicas de priv)

2022-10-31 19:58 UTC, manu-yaff commented
@kiwis08 creo que tengo presionar 2 veces "Mi cuenta"  para que me mandé a la siguiente pantalla @juandatorr99 checa a ver si a ti también te pasa

2022-10-31 20:29 UTC, manu-yaff commented on lib/src/shared/models/user_model.dart
> +      surname: "",
Este sampleUser creo que estaría mejor que estuviera en algún otro lado, por ejemplo en un controller o no se si hacer las propiedades nullable sea viable. Creo que el model sólo debería tener los contructores con sus propiedades. Dónde más se podría meter este sampleUser?

2022-10-31 20:31 UTC, manu-yaff commented on lib/src/shared/components/alcancia_snack_bar.dart
> +  return SnackBar(
Está coool este widget

2022-10-31 20:32 UTC, manu-yaff commented on lib/src/shared/provider/router_provider.dart
> +        final creatingAccount = state.subloc == createAccountLoc;
@juandatorr99 experto en routing revisa esto

2022-10-31 20:33 UTC, manu-yaff reviewed
Dejé unos comentarios nuevos en cuánto a código, pero de funcionalidad ya lo veo bien

2022-10-31 20:34 UTC, manu-yaff approved these changes

2022-11-04 07:52 UTC, merged