feat: fetch balance every 10 seconds
Alcancia-io/alcancia pull request #37
Opened 2022-10-27 00:46 UTC by juandatorr99

## Summary
The balance is fetched every 10 seconds in the dashboard screen. This was a petition from Juandi and was made previously in the testflight branch but it is being added to develop through this PR.
For it to work I had to initialize the userservice in each of the functions that use it because if this is not done the graphql cache will show always the same result.

## Requirements
Make sure you are in the latest version of the backend or consuming the deployed backend.

## Type of change
- [x ] feature
- [ ] hotfix
- [ ] fix
- [ ] refactor
- [ ] chore
- [ ] docs

## How to test?
Run the app, go to dashboard and wait 10 seconds for it to change

## How has this been tested?
_list the test you performed to test your changes_

- [ ] Balance should display 0 for new users_
- [ ] Balance should change every 10 seconds for a01209400@itesm.mx user

## Checklist (for the reviewer)

- [ ] Does the code compile without errors or warnings?
- [ ] Does the PR is free of merge conflicts?
- [ ] Does the UI is responsive?
- [ ] Is the PR modular?

2022-10-27 22:07 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_controller.dart
> +      print(response);
Borremos ese print

2022-10-27 22:15 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +      ref.watch(balanceProvider.notifier).setBalance(Balance(balance: balance));
Veo que hay provider para el balance, no es mejor meterlo en el mismo provider del user?

![imagen](https://user-images.githubusercontent.com/38588601/198408217-a380da68-230b-4bc1-8320-b21ce8030787.png)

2022-10-27 22:17 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +import 'dart:developer';
Está línea no se usa

2022-10-27 22:17 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +import 'package:alcancia/src/features/registration/model/GraphQLConfig.dart';
Está tampoco

2022-10-27 22:20 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +import 'package:alcancia/src/shared/graphql/queries/walletbalance_query.dart';
Creo que está tampoco

2022-10-27 22:20 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +import 'package:alcancia/src/shared/services/storage_service.dart';
Está tampoco

2022-10-27 22:20 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +import 'package:graphql_flutter/graphql_flutter.dart';
Está tampoco

2022-10-27 22:22 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +      _isLoading = true;
Debe haber alguna manera de poner esto en otro archivo. Se me ocurrió que tal vez se puede hacer que la clase del controller extienda de ConsumerState<>. Por ahora te la valgo jajaja, lo checamos después

2022-10-27 22:23 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +      print(balance);
Ya que estás aquí, mata ese print también jaja

2022-10-27 22:33 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_screen.dart
> +        _error = err.toString();
Aquí no se si deberíamos separar los errores, es decir, mostrar el error de fetchBalance y de fetchUserInformation por separado. Qué será mejor UX?

2022-10-27 22:39 UTC, manu-yaff commented on lib/src/shared/components/dashboard/dashboard_card.dart
> +    var balance = userBalance?.balance == 0.0
Cuando ocurre un error, si el provider no tiene nada podría "tronar" la app cuando intente hacer render de la variable _balance_. En teoría no pasa por la condición del dashboard screen, pero hay que ponerlo bien porque si por alguna razón no sale el error pero tampoco se tiene un balance en el provider creo que se romperá

2022-10-27 22:41 UTC, manu-yaff commented on lib/src/shared/components/dashboard/dashboard_card.dart
> +                fontSize: 30,
Este cambio es justificado en el figma? Sino, ya no quedarán uniformes los textos. Si quieres puedes hacer lo que habíamos platicado(hace como un mes) de hacer un AppTheme personalizado para todas los textos y colores

2022-10-27 22:43 UTC, manu-yaff commented on lib/src/shared/provider/balance_provider.dart
> +  factory Balance.fromJSON(Map<String, dynamic>? map) {
Creeeeo que no necesitamos este provider, ni este fromJSON, como es un sólo valor puedes castearlo a double directo, qué opinas?

2022-10-27 22:44 UTC, manu-yaff commented on lib/src/shared/provider/router_provider.dart
> +  print(result.hasException);
encontré otro print

2022-10-27 22:47 UTC, manu-yaff commented on lib/src/shared/provider/router_provider.dart
> +        final isRegister = state.location == "/registration";
Qué está pasando con el router? @kiwis08 también lo movió en el PR https://github.com/Alcancia-io/alcancia/pull/35

Igual, diría que ese cambio no va en este PR

2022-10-27 22:47 UTC, manu-yaff commented on lib/src/shared/provider/user_provider.dart
> +    print("Balnc ${balance}");
Este es el que decía que podría usarse, en lugar de hacer otro provider

2022-10-27 22:51 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_controller.dart
> +    UserService userService = UserService();
Cómo está el error que comentas de que siempre muestra el mismo balance por el cache? Es por el token?

2022-10-27 22:53 UTC, manu-yaff reviewed
Dejé unos comentarios, saludos

2022-10-27 22:54 UTC, manu-yaff requested changes
Dejé unos comentarios, saludos!

2022-10-28 18:43 UTC, juandatorr99 commented on lib/src/screens/dashboard/dashboard_screen.dart
> +      ref.watch(balanceProvider.notifier).setBalance(Balance(balance: balance));
Cuando lo meto en el del user no se actualiza. No funciona, ya habiamos hablado de esto

2022-10-28 18:45 UTC, juandatorr99 commented on lib/src/shared/components/dashboard/dashboard_card.dart
> +                fontSize: 30,
Es para que quepan tantos decimales. En el figma solo esta con 2

2022-10-28 18:46 UTC, juandatorr99 commented on lib/src/shared/provider/balance_provider.dart
> +  factory Balance.fromJSON(Map<String, dynamic>? map) {
Si ese no se usa entonces lo voy a corregir

2022-10-28 18:48 UTC, juandatorr99 commented on lib/src/screens/dashboard/dashboard_controller.dart
> +    UserService userService = UserService();
Es porque cuando se inicializa el userservice se configura el graphql. Luego te muestro el error pero creo que es por la cache

2022-10-28 18:52 UTC, juandatorr99 commented on lib/src/screens/dashboard/dashboard_screen.dart
> +        _error = err.toString();
bueno en realidad no deberiamos mostrar errores en este

2022-10-28 18:54 UTC, juandatorr99 commented on lib/src/screens/dashboard/dashboard_screen.dart
> +      _isLoading = true;
Jajaja ok

2022-10-28 19:01 UTC, kiwis08 commented on lib/src/screens/dashboard/dashboard_controller.dart
> +    return Future.error('Error getting balance');
Alguna razón por la que ya no regresamos el exception si hay alguno? Veo que desde el refactor ya no se checa eso.

2022-10-28 19:14 UTC, juandatorr99 commented on lib/src/shared/provider/user_provider.dart
> +    print("Balnc ${balance}");
Si lo intente pero cuando se setea no cambia en el dashboard card

2022-10-28 19:16 UTC, juandatorr99 commented on lib/src/shared/provider/router_provider.dart
> +        final isRegister = state.location == "/registration";
Si es cierto que este cambio no va aqui pero corrige el error que teniamos de que no sacaba al user del dashboard cuando no estaba autenticado

2022-10-28 19:29 UTC, juandatorr99 commented on lib/src/screens/dashboard/dashboard_controller.dart
> +    return Future.error('Error getting balance');
@manu-yaff

2022-10-28 21:48 UTC, juandatorr99 commented on lib/src/shared/components/dashboard/dashboard_card.dart
> +    var balance = userBalance?.balance == 0.0
Ya quedo esto solucionado. Antes de hacer la asignación revisa si es nulo. Si si lo es muestra un 0.0

2022-10-31 20:56 UTC, manu-yaff commented on lib/src/screens/dashboard/dashboard_controller.dart
> +    return Future.error('Error getting balance');
Creo que lo había quitado porque la exception es diferente, a veces puede venir en el graphql.errors o en otras en el linkException, pero tienes razón, hay que buscar forma de incluirla para que el mensaje de error sea más descriptivo. Hice una tarea en el clickup

2022-10-31 21:00 UTC, manu-yaff commented on lib/src/shared/components/dashboard/dashboard_card.dart
> +                fontSize: 30,
okok

2022-10-31 21:06 UTC, manu-yaff approved these changes
Sólo tengo dos comentarios:
- Sigo creyendo que no vale la pena tener un provider sólo para el balance, pero lo revisamos después si quieres
- Ponte de acuerdo con @kiwis08 porque movieron lo mismo en el redirect

2022-10-31 23:35 UTC, merged