feat: ramp url y new app icon
Alcancia-io/alcancia pull request #38
Opened 2022-11-01 19:47 UTC by juandatorr99

## Summary
_Briefly describe your changes. Please also include relevant motivation and context_
Redirection to ramp via URL
## Requirements
_list any dependencies necessary to review the changes_
- _eg. make sure you reaplace your `.env` with the latest version_
N/A
## Type of change
- [x] feature
- [ ] hotfix
- [ ] fix
- [ ] refactor
- [ ] chore
- [ ] docs

## How to test?
_describe the steps the reviewer should follow to test your changes_
- _eg Run the app, login, go to dashboard..._
Go to swap and select to pay by card, it should go to the browser
## How has this been tested?
_list the test you performed to test your changes_
By buying crypto through ramp

- [ ] _eg balance should display 0 for new users_
- [ ] Should redirect to ramp
- [ ] Test C

## Screenshots
_add screenshots if need it_

## Checklist (for the reviewer)

- [ ] Does the code compile without errors or warnings?
- [ ] Does the PR is free of merge conflicts?
- [ ] Does the UI is responsive?
- [ ] Is the PR modular?

2022-11-03 15:52 UTC, manu-yaff requested changes

2022-11-03 15:52 UTC, manu-yaff commented on lib/src/features/swap/presentation/swap_screen.dart
> +                                      "https://ri-widget-staging.firebaseapp.com/?userAddress=${user?.walletAddress}&userEmailAddress=${user?.email}&fiatValue=${usdc?.toStringAsFixed(2)}&fiatCurrency
Creo que este url de ramp deberíamos ponerlo en el .env y también estaría bueno poner este url en una variable porque está infinitamente largo jajaja

2022-11-03 15:53 UTC, manu-yaff commented on lib/src/features/swap/presentation/swap_screen.dart
> +                                      "https://ri-widget-staging.firebaseapp.com/?userAddress=${user?.walletAddress}&userEmailAddress=${user?.email}&fiatValue=${usdc?.toStringAsFixed(2)}&fiatCurrency
Igual no se si deberíamos hacer merge de ese url, ya que todavía no tenemos el key 🤕

2022-11-03 16:07 UTC, manu-yaff commented on lib/src/features/swap/presentation/swap_screen.dart
> +                                      "https://ri-widget-staging.firebaseapp.com/?userAddress=${user?.walletAddress}&userEmailAddress=${user?.email}&fiatValue=${usdc?.toStringAsFixed(2)}&fiatCurrency
Nos faltó la validación de el field para la cantidad a covertir no sea empty

2022-11-08 19:59 UTC, juandatorr99 commented on lib/src/features/swap/presentation/swap_screen.dart
> +                                      "https://ri-widget-staging.firebaseapp.com/?userAddress=${user?.walletAddress}&userEmailAddress=${user?.email}&fiatValue=${usdc?.toStringAsFixed(2)}&fiatCurrency
True, entonces dejemoslo sin mergear

2022-11-08 19:59 UTC, closed without merging