Fix/late user verification
Alcancia-io/alcancia pull request #44
Opened 2022-12-22 20:05 UTC by kiwis08

## Summary
Sends unverified user to OTP screen to finish sign up verification process after attempting to login.

## Requirements
N/A

## Type of change
- [ ] feature
- [ ] hotfix
- [x] fix
- [ ] refactor
- [ ] chore
- [ ] docs

## How to test?
Register a new account without verifying the phone number, close the app, open the app again and try to login with the new account. The app should send you to the OTP screen and ask for the verification code again.

## How has this been tested?
- [ ] Unverified account sends to OTP
- [ ] Verified account sends to MFA screen

## Screenshots
N/A

## Checklist (for the reviewer)

- [ ] Does the code compile without errors or warnings?
- [ ] Does the PR is free of merge conflicts?
- [ ] Does the UI is responsive?
- [ ] Is the PR modular?

2022-12-23 20:32 UTC, manu-yaff requested changes
Me salió este error @kiwis08 al intentar ingresar el número

![imagen](https://user-images.githubusercontent.com/38588601/209403075-709d3bf0-046f-40fa-90c8-e5bda71b7cc9.png)

2023-01-02 20:29 UTC, kiwis08 commented
@manu-yaff nomas hice los cambios del modelo del usuario (los nuevos id) pero no puedo replicar ese error al registrarme. Puedes checar otra vez?

2023-01-02 22:46 UTC, manu-yaff commented
> @manu-yaff nomas hice los cambios del modelo del usuario (los nuevos id) pero no puedo replicar ese error al registrarme. Puedes checar otra vez?

con que rama del back debería probarlo?

2023-01-02 23:27 UTC, kiwis08 commented
> > @manu-yaff nomas hice los cambios del modelo del usuario (los nuevos id) pero no puedo replicar ese error al registrarme. Puedes checar otra vez?
> 
> con que rama del back debería probarlo?

lo he estado probando con el PR de kycVerified

2023-01-06 19:31 UTC, manu-yaff approved these changes

2023-01-06 19:38 UTC, merged