feat: add APY for target currencies
Alcancia-io/alcancia pull request #64
Opened 2023-01-30 03:07 UTC by manu-yaff

## Summary
- added APY for target currencies, fetched from api

## Requirements
backend branch: chore/OINK-NA-add-aPolUSDC-to-APY-endpoint

## Type of change
- [x] feature
- [ ] hotfix
- [ ] fix
- [ ] refactor
- [ ] chore
- [ ] docs

## How to test?
- go to swap, you should see APY for selected target currency

## Screenshots
<img width="370" alt="imagen" src="https://user-images.githubusercontent.com/38588601/215379099-881308fa-0acf-4999-a96f-4da700685193.png">

<img width="346" alt="imagen" src="https://user-images.githubusercontent.com/38588601/215379119-ceb5a72d-2805-47eb-aa5c-627953402341.png">

## Checklist (for the reviewer)

- [ ] Does the code compile without errors or warnings?
- [ ] Does the PR is free of merge conflicts?
- [ ] Does the UI is responsive?
- [ ] Is the PR modular?

2023-01-31 00:03 UTC, kiwis08 requested changes

2023-01-31 00:03 UTC, kiwis08 commented on lib/src/screens/swap/components/currency_risk_card.dart
> +                const TextSpan(text: 'Nivel de riesgo: '),
Este texto es blanco y no se ve en light mode

2023-01-31 00:03 UTC, kiwis08 commented on lib/src/screens/swap/components/currency_risk_card.dart
> +    var riskLevelColor = riskLevel == RiskLevel.bajo ? const Color(0xff00FF98) : const Color(0xffA0FF26);
El color de 'medio' no se ve bien en light mode

2023-01-31 03:03 UTC, manu-yaff commented on lib/src/screens/swap/components/currency_risk_card.dart
> +    var riskLevelColor = riskLevel == RiskLevel.bajo ? const Color(0xff00FF98) : const Color(0xffA0FF26);
ya cambié los colores, ya debe verse bien el texto y los colores

2023-02-03 23:22 UTC, kiwis08 approved these changes

2023-02-03 23:59 UTC, merged